/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VariationsRouteImport } from './routes/variations'
import { Route as TaminotRouteImport } from './routes/taminot'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MasterZayavkaRouteImport } from './routes/master-zayavka'
import { Route as MasterJadvalRouteImport } from './routes/master-jadval'
import { Route as DavomatRouteImport } from './routes/davomat'
import { Route as BuxalteriyaRouteImport } from './routes/buxalteriya'
import { Route as BrigadeBalanceRouteImport } from './routes/brigade-balance'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as AiAgentRouteImport } from './routes/ai-agent'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TgMiniappRouteImport } from './routes/tg.miniapp'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as ApiPublicZayavkaCallbackRouteImport } from './routes/api/public/zayavka-callback'
import { Route as ApiPublicTgSubmitRouteImport } from './routes/api/public/tg-submit'
import { Route as ApiPublicTgMetaRouteImport } from './routes/api/public/tg-meta'
import { Route as ApiPublicTelegramWebhookSecretRouteImport } from './routes/api/public/telegram-webhook.$secret'

const VariationsRoute = VariationsRouteImport.update({
  id: '/variations',
  path: '/variations',
  getParentRoute: () => rootRouteImport,
} as any)
const TaminotRoute = TaminotRouteImport.update({
  id: '/taminot',
  path: '/taminot',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterZayavkaRoute = MasterZayavkaRouteImport.update({
  id: '/master-zayavka',
  path: '/master-zayavka',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterJadvalRoute = MasterJadvalRouteImport.update({
  id: '/master-jadval',
  path: '/master-jadval',
  getParentRoute: () => rootRouteImport,
} as any)
const DavomatRoute = DavomatRouteImport.update({
  id: '/davomat',
  path: '/davomat',
  getParentRoute: () => rootRouteImport,
} as any)
const BuxalteriyaRoute = BuxalteriyaRouteImport.update({
  id: '/buxalteriya',
  path: '/buxalteriya',
  getParentRoute: () => rootRouteImport,
} as any)
const BrigadeBalanceRoute = BrigadeBalanceRouteImport.update({
  id: '/brigade-balance',
  path: '/brigade-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAgentRoute = AiAgentRouteImport.update({
  id: '/ai-agent',
  path: '/ai-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TgMiniappRoute = TgMiniappRouteImport.update({
  id: '/tg/miniapp',
  path: '/tg/miniapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicZayavkaCallbackRoute =
  ApiPublicZayavkaCallbackRouteImport.update({
    id: '/api/public/zayavka-callback',
    path: '/api/public/zayavka-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTgSubmitRoute = ApiPublicTgSubmitRouteImport.update({
  id: '/api/public/tg-submit',
  path: '/api/public/tg-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTgMetaRoute = ApiPublicTgMetaRouteImport.update({
  id: '/api/public/tg-meta',
  path: '/api/public/tg-meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookSecretRoute =
  ApiPublicTelegramWebhookSecretRouteImport.update({
    id: '/api/public/telegram-webhook/$secret',
    path: '/api/public/telegram-webhook/$secret',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-agent': typeof AiAgentRoute
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRoute
  '/brigade-balance': typeof BrigadeBalanceRoute
  '/buxalteriya': typeof BuxalteriyaRoute
  '/davomat': typeof DavomatRoute
  '/master-jadval': typeof MasterJadvalRoute
  '/master-zayavka': typeof MasterZayavkaRoute
  '/settings': typeof SettingsRoute
  '/taminot': typeof TaminotRoute
  '/variations': typeof VariationsRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/tg/miniapp': typeof TgMiniappRoute
  '/api/public/tg-meta': typeof ApiPublicTgMetaRoute
  '/api/public/tg-submit': typeof ApiPublicTgSubmitRoute
  '/api/public/zayavka-callback': typeof ApiPublicZayavkaCallbackRoute
  '/api/public/telegram-webhook/$secret': typeof ApiPublicTelegramWebhookSecretRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-agent': typeof AiAgentRoute
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRoute
  '/brigade-balance': typeof BrigadeBalanceRoute
  '/buxalteriya': typeof BuxalteriyaRoute
  '/davomat': typeof DavomatRoute
  '/master-jadval': typeof MasterJadvalRoute
  '/master-zayavka': typeof MasterZayavkaRoute
  '/settings': typeof SettingsRoute
  '/taminot': typeof TaminotRoute
  '/variations': typeof VariationsRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/tg/miniapp': typeof TgMiniappRoute
  '/api/public/tg-meta': typeof ApiPublicTgMetaRoute
  '/api/public/tg-submit': typeof ApiPublicTgSubmitRoute
  '/api/public/zayavka-callback': typeof ApiPublicZayavkaCallbackRoute
  '/api/public/telegram-webhook/$secret': typeof ApiPublicTelegramWebhookSecretRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-agent': typeof AiAgentRoute
  '/audit-log': typeof AuditLogRoute
  '/auth': typeof AuthRoute
  '/brigade-balance': typeof BrigadeBalanceRoute
  '/buxalteriya': typeof BuxalteriyaRoute
  '/davomat': typeof DavomatRoute
  '/master-jadval': typeof MasterJadvalRoute
  '/master-zayavka': typeof MasterZayavkaRoute
  '/settings': typeof SettingsRoute
  '/taminot': typeof TaminotRoute
  '/variations': typeof VariationsRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/tg/miniapp': typeof TgMiniappRoute
  '/api/public/tg-meta': typeof ApiPublicTgMetaRoute
  '/api/public/tg-submit': typeof ApiPublicTgSubmitRoute
  '/api/public/zayavka-callback': typeof ApiPublicZayavkaCallbackRoute
  '/api/public/telegram-webhook/$secret': typeof ApiPublicTelegramWebhookSecretRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-agent'
    | '/audit-log'
    | '/auth'
    | '/brigade-balance'
    | '/buxalteriya'
    | '/davomat'
    | '/master-jadval'
    | '/master-zayavka'
    | '/settings'
    | '/taminot'
    | '/variations'
    | '/api/stt'
    | '/api/tts'
    | '/tg/miniapp'
    | '/api/public/tg-meta'
    | '/api/public/tg-submit'
    | '/api/public/zayavka-callback'
    | '/api/public/telegram-webhook/$secret'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-agent'
    | '/audit-log'
    | '/auth'
    | '/brigade-balance'
    | '/buxalteriya'
    | '/davomat'
    | '/master-jadval'
    | '/master-zayavka'
    | '/settings'
    | '/taminot'
    | '/variations'
    | '/api/stt'
    | '/api/tts'
    | '/tg/miniapp'
    | '/api/public/tg-meta'
    | '/api/public/tg-submit'
    | '/api/public/zayavka-callback'
    | '/api/public/telegram-webhook/$secret'
  id:
    | '__root__'
    | '/'
    | '/ai-agent'
    | '/audit-log'
    | '/auth'
    | '/brigade-balance'
    | '/buxalteriya'
    | '/davomat'
    | '/master-jadval'
    | '/master-zayavka'
    | '/settings'
    | '/taminot'
    | '/variations'
    | '/api/stt'
    | '/api/tts'
    | '/tg/miniapp'
    | '/api/public/tg-meta'
    | '/api/public/tg-submit'
    | '/api/public/zayavka-callback'
    | '/api/public/telegram-webhook/$secret'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAgentRoute: typeof AiAgentRoute
  AuditLogRoute: typeof AuditLogRoute
  AuthRoute: typeof AuthRoute
  BrigadeBalanceRoute: typeof BrigadeBalanceRoute
  BuxalteriyaRoute: typeof BuxalteriyaRoute
  DavomatRoute: typeof DavomatRoute
  MasterJadvalRoute: typeof MasterJadvalRoute
  MasterZayavkaRoute: typeof MasterZayavkaRoute
  SettingsRoute: typeof SettingsRoute
  TaminotRoute: typeof TaminotRoute
  VariationsRoute: typeof VariationsRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsRoute: typeof ApiTtsRoute
  TgMiniappRoute: typeof TgMiniappRoute
  ApiPublicTgMetaRoute: typeof ApiPublicTgMetaRoute
  ApiPublicTgSubmitRoute: typeof ApiPublicTgSubmitRoute
  ApiPublicZayavkaCallbackRoute: typeof ApiPublicZayavkaCallbackRoute
  ApiPublicTelegramWebhookSecretRoute: typeof ApiPublicTelegramWebhookSecretRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/variations': {
      id: '/variations'
      path: '/variations'
      fullPath: '/variations'
      preLoaderRoute: typeof VariationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taminot': {
      id: '/taminot'
      path: '/taminot'
      fullPath: '/taminot'
      preLoaderRoute: typeof TaminotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-zayavka': {
      id: '/master-zayavka'
      path: '/master-zayavka'
      fullPath: '/master-zayavka'
      preLoaderRoute: typeof MasterZayavkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master-jadval': {
      id: '/master-jadval'
      path: '/master-jadval'
      fullPath: '/master-jadval'
      preLoaderRoute: typeof MasterJadvalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/davomat': {
      id: '/davomat'
      path: '/davomat'
      fullPath: '/davomat'
      preLoaderRoute: typeof DavomatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buxalteriya': {
      id: '/buxalteriya'
      path: '/buxalteriya'
      fullPath: '/buxalteriya'
      preLoaderRoute: typeof BuxalteriyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brigade-balance': {
      id: '/brigade-balance'
      path: '/brigade-balance'
      fullPath: '/brigade-balance'
      preLoaderRoute: typeof BrigadeBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-agent': {
      id: '/ai-agent'
      path: '/ai-agent'
      fullPath: '/ai-agent'
      preLoaderRoute: typeof AiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tg/miniapp': {
      id: '/tg/miniapp'
      path: '/tg/miniapp'
      fullPath: '/tg/miniapp'
      preLoaderRoute: typeof TgMiniappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/zayavka-callback': {
      id: '/api/public/zayavka-callback'
      path: '/api/public/zayavka-callback'
      fullPath: '/api/public/zayavka-callback'
      preLoaderRoute: typeof ApiPublicZayavkaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tg-submit': {
      id: '/api/public/tg-submit'
      path: '/api/public/tg-submit'
      fullPath: '/api/public/tg-submit'
      preLoaderRoute: typeof ApiPublicTgSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tg-meta': {
      id: '/api/public/tg-meta'
      path: '/api/public/tg-meta'
      fullPath: '/api/public/tg-meta'
      preLoaderRoute: typeof ApiPublicTgMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram-webhook/$secret': {
      id: '/api/public/telegram-webhook/$secret'
      path: '/api/public/telegram-webhook/$secret'
      fullPath: '/api/public/telegram-webhook/$secret'
      preLoaderRoute: typeof ApiPublicTelegramWebhookSecretRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAgentRoute: AiAgentRoute,
  AuditLogRoute: AuditLogRoute,
  AuthRoute: AuthRoute,
  BrigadeBalanceRoute: BrigadeBalanceRoute,
  BuxalteriyaRoute: BuxalteriyaRoute,
  DavomatRoute: DavomatRoute,
  MasterJadvalRoute: MasterJadvalRoute,
  MasterZayavkaRoute: MasterZayavkaRoute,
  SettingsRoute: SettingsRoute,
  TaminotRoute: TaminotRoute,
  VariationsRoute: VariationsRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsRoute: ApiTtsRoute,
  TgMiniappRoute: TgMiniappRoute,
  ApiPublicTgMetaRoute: ApiPublicTgMetaRoute,
  ApiPublicTgSubmitRoute: ApiPublicTgSubmitRoute,
  ApiPublicZayavkaCallbackRoute: ApiPublicZayavkaCallbackRoute,
  ApiPublicTelegramWebhookSecretRoute: ApiPublicTelegramWebhookSecretRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
